import MovieList from "./MovieList";


const movie_data = {
  titles: [
    {
      id: "tt13623632",
      type: "tvSeries",
      primaryTitle: "Alien: Earth",
      originalTitle: "Alien: Earth",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BOGIyNGRiNzgtOWQxZC00YzJmLThlZTYtYTMyMDk0YWZjMTk5XkEyXkFqcGc@._V1_.jpg",
        width: 675,
        height: 1000,
      },
      startYear: 2025,
      runtimeSeconds: 3300,
      genres: ["Horror", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 7.3,
        voteCount: 66868,
      },
      plot: "When a mysterious space vessel crash-lands on Earth, a young woman and a ragtag group of tactical soldiers make a fateful discovery that puts them face-to-face with the planet's greatest threat.",
    },
    {
      id: "tt10795658",
      type: "tvSeries",
      primaryTitle: "Alice in Borderland",
      originalTitle: "Imawa no Kuni no Arisu",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYmMzODA4M2MtMjBmNC00YjFhLTg4NzgtODgyNzE4NWQxMThmXkEyXkFqcGc@._V1_.jpg",
        width: 1500,
        height: 2222,
      },
      startYear: 2020,
      runtimeSeconds: 3000,
      genres: ["Action", "Drama", "Horror", "Mystery", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 7.8,
        voteCount: 131453,
      },
      plot: "Arisu - a listless, jobless and video-game-obsessed young man - suddenly finds himself in a strange, emptied-out version of Tokyo in which he and his friends must compete in dangerous games in order to survive.",
    },
    {
      id: "tt4574334",
      type: "tvSeries",
      primaryTitle: "Stranger Things",
      originalTitle: "Stranger Things",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMjg2NmM0MTEtYWY2Yy00NmFlLTllNTMtMjVkZjEwMGVlNzdjXkEyXkFqcGc@._V1_.jpg",
        width: 1500,
        height: 2222,
      },
      startYear: 2016,
      endYear: 2025,
      runtimeSeconds: 3600,
      genres: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 8.6,
        voteCount: 1488742,
      },
      plot: "In 1980s Indiana, a group of young friends witness supernatural forces and secret government exploits. As they search for answers, the children unravel a series of extraordinary mysteries.",
    },
    {
      id: "tt32499579",
      type: "tvSeries",
      primaryTitle: "Haunted Hotel",
      originalTitle: "Haunted Hotel",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYjlmZDkzMmEtYTY2OS00NDAyLWE5ZjQtZGZiYjNiM2NmNmJkXkEyXkFqcGc@._V1_.jpg",
        width: 1500,
        height: 2222,
      },
      startYear: 2025,
      runtimeSeconds: 1500,
      genres: ["Animation", "Comedy", "Horror"],
      rating: {
        aggregateRating: 7.7,
        voteCount: 3115,
      },
      plot: "A single mom with two kids operates a haunted hotel, aided by her late brother's ghost who believes they can have ingenious ideas despite his ethereal state.",
    },
    {
      id: "tt0460681",
      type: "tvSeries",
      primaryTitle: "Supernatural",
      originalTitle: "Supernatural",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMDFmMGZmMGItNGRjNC00NjVjLWI5ODEtNzhjMTE5MmJhN2FkXkEyXkFqcGc@._V1_.jpg",
        width: 423,
        height: 616,
      },
      startYear: 2005,
      endYear: 2020,
      runtimeSeconds: 2640,
      genres: ["Drama", "Fantasy", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 8.4,
        voteCount: 522804,
      },
      plot: "Two brothers follow their father's footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.",
    },
    {
      id: "tt2560140",
      type: "tvSeries",
      primaryTitle: "Attack on Titan",
      originalTitle: "Shingeki no Kyojin",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZjliODY5MzQtMmViZC00MTZmLWFhMWMtMjMwM2I3OGY1MTRiXkEyXkFqcGc@._V1_.jpg",
        width: 850,
        height: 1200,
      },
      startYear: 2013,
      endYear: 2023,
      runtimeSeconds: 1440,
      genres: [
        "Animation",
        "Action",
        "Adventure",
        "Drama",
        "Fantasy",
        "Horror",
      ],
      rating: {
        aggregateRating: 9.1,
        voteCount: 650106,
      },
      plot: "After his hometown is destroyed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    },
    {
      id: "tt1520211",
      type: "tvSeries",
      primaryTitle: "The Walking Dead",
      originalTitle: "The Walking Dead",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYWQwMGRhNGEtZTNhMy00MzVjLWJhMjItYjcwMDljMTkyNTg2XkEyXkFqcGc@._V1_.jpg",
        width: 2000,
        height: 3000,
      },
      startYear: 2010,
      endYear: 2022,
      runtimeSeconds: 2700,
      genres: ["Drama", "Horror", "Thriller"],
      rating: {
        aggregateRating: 8.1,
        voteCount: 1163433,
      },
      plot: "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
    },
    {
      id: "tt19244304",
      type: "tvSeries",
      primaryTitle: "IT: Welcome to Derry",
      originalTitle: "IT: Welcome to Derry",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZWE0ZWM1MjUtNmYzYS00NzU3LTkxYmQtNmI3NTc0ZTY1NmVlXkEyXkFqcGc@._V1_.jpg",
        width: 1638,
        height: 2048,
      },
      startYear: 2025,
      genres: ["Horror"],
      plot: "It will follow the events in the 1960s, the time leading up to the events of the first film in the Stephen King It series.",
    },
    {
      id: "tt3581920",
      type: "tvSeries",
      primaryTitle: "The Last of Us",
      originalTitle: "The Last of Us",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYWI3ODJlMzktY2U5NC00ZjdlLWE1MGItNWQxZDk3NWNjN2RhXkEyXkFqcGc@._V1_.jpg",
        width: 1383,
        height: 2048,
      },
      startYear: 2023,
      runtimeSeconds: 3000,
      genres: ["Action", "Adventure", "Drama", "Horror", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 8.5,
        voteCount: 699817,
      },
      plot: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    },
    {
      id: "tt9813792",
      type: "tvSeries",
      primaryTitle: "From",
      originalTitle: "From",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYzM5ZWMxOGEtZjEyMC00YjQ0LThiYjEtZjVkZGEzN2NlOGEwXkEyXkFqcGc@._V1_.jpg",
        width: 1296,
        height: 1920,
      },
      startYear: 2022,
      runtimeSeconds: 3120,
      genres: ["Drama", "Horror", "Mystery", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 7.8,
        voteCount: 153638,
      },
      plot: "Unravel the mystery of a city in middle U.S.A. that imprisons everyone who enters. As the residents struggle to maintain a sense of normality and seek a way out, they must also survive the threats of the surrounding forest.",
    },
    {
      id: "tt1844624",
      type: "tvSeries",
      primaryTitle: "American Horror Story",
      originalTitle: "American Horror Story",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNzJjZTg0ZmMtMTg0Ny00NzYxLWFjMWMtMWFiYmNkMTNjZGMyXkEyXkFqcGc@._V1_.jpg",
        width: 592,
        height: 864,
      },
      startYear: 2011,
      runtimeSeconds: 3600,
      genres: ["Drama", "Horror", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 7.9,
        voteCount: 357407,
      },
      plot: "An anthology horror drama series centering on different characters and locations, showcasing different aspects of horror. Created and produced by Ryan Murphy and Brad Falchuk.",
    },
    {
      id: "tt1751634",
      type: "tvSeries",
      primaryTitle: "The Sandman",
      originalTitle: "The Sandman",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNjk0M2ZhZTQtZjQ0NC00ODA2LWFkN2ItMTA0ZTc0MjJjODg0XkEyXkFqcGc@._V1_.jpg",
        width: 1500,
        height: 2222,
      },
      startYear: 2022,
      endYear: 2025,
      runtimeSeconds: 2700,
      genres: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi"],
      rating: {
        aggregateRating: 7.7,
        voteCount: 203296,
      },
      plot: "Upon escaping after decades of imprisonment by a mortal wizard, Dream, the personification of dreams, sets about to reclaim his lost equipment.",
    },
    {
      id: "tt13062500",
      type: "tvSeries",
      primaryTitle: "The Walking Dead: Daryl Dixon",
      originalTitle: "The Walking Dead: Daryl Dixon",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZjFlYzg4M2ItZjlmZC00MTA2LWJlZTgtODdlZmZjNWRkMzI5XkEyXkFqcGc@._V1_.jpg",
        width: 1040,
        height: 1560,
      },
      startYear: 2023,
      endYear: 2026,
      runtimeSeconds: 2820,
      genres: ["Drama", "Horror"],
      rating: {
        aggregateRating: 7.5,
        voteCount: 35551,
      },
      plot: "Daryl's journey across a broken but resilient France as he hopes to find a way back home.",
    },
    {
      id: "tt1405406",
      type: "tvSeries",
      primaryTitle: "The Vampire Diaries",
      originalTitle: "The Vampire Diaries",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMmNjOWQzYmYtNGYxOS00MjVkLTg1MWUtMTkzMGE0MDgwNzQ5XkEyXkFqcGc@._V1_.jpg",
        width: 680,
        height: 1000,
      },
      startYear: 2009,
      endYear: 2017,
      runtimeSeconds: 2580,
      genres: ["Drama", "Fantasy", "Horror", "Mystery", "Romance", "Thriller"],
      rating: {
        aggregateRating: 7.7,
        voteCount: 373142,
      },
      plot: "The lives, loves, dangers and disasters in the town, Mystic Falls, Virginia. Creatures of unspeakable horror lurk beneath this town as a teenage girl is suddenly torn between two vampire brothers.",
    },
    {
      id: "tt0118276",
      type: "tvSeries",
      primaryTitle: "Buffy the Vampire Slayer",
      originalTitle: "Buffy the Vampire Slayer",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMDk4MGVkNDAtZjQwZi00MDc3LWE4MmEtY2YyODQ2NDQyMjgxXkEyXkFqcGc@._V1_.jpg",
        width: 500,
        height: 735,
      },
      startYear: 1997,
      endYear: 2003,
      runtimeSeconds: 2700,
      genres: ["Action", "Adventure", "Drama", "Fantasy", "Horror", "Romance"],
      rating: {
        aggregateRating: 8.3,
        voteCount: 170439,
      },
      plot: "A young woman, destined to slay vampires, demons and other infernal creatures, deals with her life fighting evil, with the help of her friends.",
    },
    {
      id: "tt2618986",
      type: "tvSeries",
      primaryTitle: "Wayward Pines",
      originalTitle: "Wayward Pines",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMjUwY2NmZDItZjdjNC00ZGQ3LTk2NTEtNjY5NTQxOGYwNGY4XkEyXkFqcGc@._V1_.jpg",
        width: 1000,
        height: 1481,
      },
      startYear: 2015,
      endYear: 2016,
      runtimeSeconds: 3600,
      genres: ["Drama", "Horror", "Mystery", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 7.3,
        voteCount: 63412,
      },
      plot: "A Secret Service agent goes to Wayward Pines, Idaho, in search of two federal agents who have gone missing in the bucolic town. He soon learns that he might never get out of Wayward Pines alive.",
    },
    {
      id: "tt10946316",
      type: "tvSeries",
      primaryTitle: "The Institute",
      originalTitle: "The Institute",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNzNhYzM1ZDQtYzNiYi00Y2NhLWEyMDYtNDU4MGE1YzM0YWQ4XkEyXkFqcGc@._V1_.jpg",
        width: 3036,
        height: 4498,
      },
      startYear: 2025,
      runtimeSeconds: 3300,
      genres: ["Horror", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 6.7,
        voteCount: 7896,
      },
      plot: "A teen genius wakes up in a strange place full of children who got there the same way he did, and who all, like him, possess unusual abilities.",
    },
    {
      id: "tt2243973",
      type: "tvSeries",
      primaryTitle: "Hannibal",
      originalTitle: "Hannibal",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNjBmYjdiMzItNTEwNi00YTI2LTg4YjctOTRjNDYxNTUxNGQ1XkEyXkFqcGc@._V1_.jpg",
        width: 1024,
        height: 1448,
      },
      startYear: 2013,
      endYear: 2015,
      runtimeSeconds: 2700,
      genres: ["Crime", "Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 8.5,
        voteCount: 299063,
      },
      plot: "Explores the early relationship between renowned psychiatrist Hannibal Lecter and a young FBI criminal profiler who is haunted by his ability to empathize with serial killers.",
    },
    {
      id: "tt35459966",
      type: "tvSeries",
      primaryTitle: "Knights of Guinevere",
      originalTitle: "Knights of Guinevere",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNWY1MTJkZGQtNmU0OS00NWI1LWJmZGMtOWNiNzQ4MjFjMzE5XkEyXkFqcGc@._V1_.jpg",
        width: 1013,
        height: 1320,
      },
      startYear: 2025,
      genres: [
        "Animation",
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Horror",
        "Sci-Fi",
        "Thriller",
      ],
      rating: {
        aggregateRating: 8.4,
        voteCount: 740,
      },
      plot: "In a global sky-park, two dreamers pin their hopes on a damaged Princess Android - their possible salvation or doom. A psychological thriller between the clouds and lurking shadows below.",
    },
    {
      id: "tt0052520",
      type: "tvSeries",
      primaryTitle: "The Twilight Zone",
      originalTitle: "The Twilight Zone",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZjdmOTE3NjItY2JkMi00YjlhLWI0M2UtZjEwZTQ4ZDBkM2I0XkEyXkFqcGc@._V1_.jpg",
        width: 490,
        height: 761,
      },
      startYear: 1959,
      endYear: 1964,
      runtimeSeconds: 3000,
      genres: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 9,
        voteCount: 103176,
      },
      plot: "Classic American Anthology series created by Rod Serling, featuring standalone stories of science fiction, fantasy, and horror, each with a twist ending or moral lesson.",
    },
    {
      id: "tt26545355",
      type: "tvSeries",
      primaryTitle: "Creature Commandos",
      originalTitle: "Creature Commandos",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BODVmMmM0MzUtODlhMC00Y2QwLWI0MTktZmNmY2JjYjM0OTI4XkEyXkFqcGc@._V1_.jpg",
        width: 2560,
        height: 3840,
      },
      startYear: 2024,
      runtimeSeconds: 1380,
      genres: [
        "Animation",
        "Action",
        "Adventure",
        "Comedy",
        "Horror",
        "Mystery",
        "Sci-Fi",
      ],
      rating: {
        aggregateRating: 7.8,
        voteCount: 23995,
      },
      plot: "A group of nonhuman criminals comprised of an anthropomorphic weasel, a robot, the bride of Frankenstein, a radioactive skeleton, and their human leader are tasked with stopping an evil sorceress.",
    },
    {
      id: "tt3960394",
      type: "tvSeries",
      primaryTitle: "Interview with the Vampire",
      originalTitle: "Interview with the Vampire",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BOTZlOGYwMmQtNDljNS00ZDgwLWIwMDQtMTQ2NzRiZjUyOTgzXkEyXkFqcGc@._V1_.jpg",
        width: 2025,
        height: 3000,
      },
      startYear: 2022,
      genres: ["Drama", "Fantasy", "Horror", "Romance"],
      rating: {
        aggregateRating: 7.5,
        voteCount: 34062,
      },
      plot: "A vampire tells his epic story of love, blood, and the perils of immortality to a journalist.",
    },
    {
      id: "tt9561862",
      type: "tvSeries",
      primaryTitle: "Love, Death & Robots",
      originalTitle: "Love, Death & Robots",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZDY3OTZiYzktN2U5My00MzRhLWJiZjItZjNlZmM3OGViZmFiXkEyXkFqcGc@._V1_.jpg",
        width: 1500,
        height: 2222,
      },
      startYear: 2019,
      runtimeSeconds: 900,
      genres: [
        "Animation",
        "Short",
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Horror",
        "Mystery",
        "Sci-Fi",
        "Thriller",
      ],
      rating: {
        aggregateRating: 8.4,
        voteCount: 222995,
      },
      plot: "A collection of animated short stories that span various genres including science fiction, fantasy, horror and comedy.",
    },
    {
      id: "tt33028568",
      type: "tvSeries",
      primaryTitle: "The Summer Hikaru Died",
      originalTitle: "Hikaru ga Shinda Natsu",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZDkxYzM3MTYtZmFjMy00MDIxLTllNDctODQxZDNkZDQzNTAxXkEyXkFqcGc@._V1_.jpg",
        width: 750,
        height: 1060,
      },
      startYear: 2025,
      genres: [
        "Animation",
        "Drama",
        "Horror",
        "Mystery",
        "Romance",
        "Thriller",
      ],
      rating: {
        aggregateRating: 8.1,
        voteCount: 3527,
      },
      plot: "Hikaru vanishes, replaced by an entity with his appearance, voice, and memories. The mysterious being maintains Hikaru's persona, making distinguishing it from the real Hikaru challenging as they continue their daily routines.",
    },
    {
      id: "tt7908628",
      type: "tvSeries",
      primaryTitle: "What We Do in the Shadows",
      originalTitle: "What We Do in the Shadows",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNDhiYTVlYjUtMDc4OC00NzBmLWE5YTYtNDBjZDc4MzM3YzNmXkEyXkFqcGc@._V1_.jpg",
        width: 1080,
        height: 1350,
      },
      startYear: 2019,
      endYear: 2024,
      runtimeSeconds: 1800,
      genres: ["Comedy", "Fantasy", "Horror"],
      rating: {
        aggregateRating: 8.6,
        voteCount: 122224,
      },
      plot: "A look into the nightly lives of four vampires who have lived together on Staten Island for over a century.",
    },
    {
      id: "tt8550800",
      type: "tvSeries",
      primaryTitle: "The Outsider",
      originalTitle: "The Outsider",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BOGY0YjJmOWItOGI2MS00N2VmLTlmNjYtMDM3YjY1MzkyM2E1XkEyXkFqcGc@._V1_.jpg",
        width: 1280,
        height: 1920,
      },
      startYear: 2020,
      endYear: 2020,
      runtimeSeconds: 3600,
      genres: ["Crime", "Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 7.6,
        voteCount: 110846,
      },
      plot: "When an insidious supernatural force edges its way into a seemingly straightforward investigation into the gruesome murder of a young boy, it leads a seasoned cop and an unorthodox investigator to question everything they believe in.",
    },
    {
      id: "tt2359704",
      type: "tvSeries",
      primaryTitle: "JoJo's Bizarre Adventure",
      originalTitle: "JoJo no Kimyô na Bôken",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMzIyNzY4NTMtNmVhYS00OWFhLTkwMWMtOGFkNTdmNWU2ZDdiXkEyXkFqcGc@._V1_.jpg",
        width: 750,
        height: 1071,
      },
      startYear: 2012,
      runtimeSeconds: 1440,
      genres: [
        "Animation",
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Horror",
      ],
      rating: {
        aggregateRating: 8.5,
        voteCount: 47012,
      },
      plot: "The story of the Joestar family, who are possessed with intense psychic strength, and the adventures each member encounters throughout their lives.",
    },
    {
      id: "tt14169960",
      type: "tvSeries",
      primaryTitle: "All of Us Are Dead",
      originalTitle: "Jigeum uri hakgyoneun",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZDY4ZmZhNzMtNjdkMC00NTE3LWFjYzQtOGE4OTllOGY1NTk5XkEyXkFqcGc@._V1_.jpg",
        width: 1500,
        height: 2222,
      },
      startYear: 2022,
      runtimeSeconds: 3600,
      genres: ["Action", "Drama", "Fantasy", "Horror", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 7.6,
        voteCount: 83933,
      },
      plot: "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out or turn into one of the rabid infected.",
    },
    {
      id: "tt4093826",
      type: "tvSeries",
      primaryTitle: "Twin Peaks",
      originalTitle: "Twin Peaks",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZGU5OTQ2YzctZmE4Zi00OWI0LWJmMDQtNDcxYjJmODBjN2U1XkEyXkFqcGc@._V1_.jpg",
        width: 1311,
        height: 1967,
      },
      startYear: 2017,
      endYear: 2017,
      runtimeSeconds: 3600,
      genres: ["Crime", "Drama", "Horror", "Mystery"],
      rating: {
        aggregateRating: 8.5,
        voteCount: 85650,
      },
      plot: "Picks up 25 years after the inhabitants of a quaint northwestern town are stunned when their homecoming queen is murdered.",
    },
    {
      id: "tt9055008",
      type: "tvSeries",
      primaryTitle: "Evil",
      originalTitle: "Evil",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYmZjYzZmNzktZWU0My00MWRhLWJhZGEtYWRiNjA1YjA1MGMxXkEyXkFqcGc@._V1_.jpg",
        width: 658,
        height: 820,
      },
      startYear: 2019,
      endYear: 2024,
      runtimeSeconds: 2700,
      genres: ["Crime", "Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 7.8,
        voteCount: 49816,
      },
      plot: "A skeptical psychologist and scientist join a Catholic priest-in-training to investigate the church's backlog of unexplained mysteries, miracles, and demonic possessions.",
    },
    {
      id: "tt18546730",
      type: "tvSeries",
      primaryTitle: "The Walking Dead: Dead City",
      originalTitle: "The Walking Dead: Dead City",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYWI0ZjgxYWYtODZmNi00ZWI0LWI4MmEtZDBmOTNmMTRlMjY0XkEyXkFqcGc@._V1_.jpg",
        width: 1382,
        height: 2048,
      },
      startYear: 2023,
      runtimeSeconds: 2760,
      genres: ["Action", "Adventure", "Drama", "Horror", "Thriller"],
      rating: {
        aggregateRating: 7.1,
        voteCount: 32178,
      },
      plot: "Maggie and Negan travel into a post-apocalyptic Manhattan long ago cut off from the mainland. The city is filled with the dead and denizens who have made New York City their own world.",
    },
    {
      id: "tt2632424",
      type: "tvSeries",
      primaryTitle: "The Originals",
      originalTitle: "The Originals",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZDJkYjg3MDItMjhiMi00NjhjLThlM2EtNzUxNzcyNDJjN2ZhXkEyXkFqcGc@._V1_.jpg",
        width: 1000,
        height: 1500,
      },
      startYear: 2013,
      endYear: 2018,
      runtimeSeconds: 2700,
      genres: ["Drama", "Fantasy", "Horror", "Mystery"],
      rating: {
        aggregateRating: 8.2,
        voteCount: 157089,
      },
      plot: "A family of power-hungry thousand-year-old vampires look to take back the city that they built and dominate all those who have done them wrong.",
    },
    {
      id: "tt7569592",
      type: "tvSeries",
      primaryTitle: "Chilling Adventures of Sabrina",
      originalTitle: "Chilling Adventures of Sabrina",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BOTQyMDYwNDMyOV5BMl5BanBnXkFtZTgwMjM4NTIzNjM@._V1_.jpg",
        width: 1382,
        height: 2048,
      },
      startYear: 2018,
      endYear: 2020,
      runtimeSeconds: 3600,
      genres: ["Drama", "Fantasy", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 7.4,
        voteCount: 116089,
      },
      plot: "As her 16th birthday nears, Sabrina Spellman must reconcile her dual nature as a half-witch, half-mortal while fighting the evil forces that threaten her, her family, and the daylight world humans inhabit.",
    },
    {
      id: "tt2188671",
      type: "tvSeries",
      primaryTitle: "Bates Motel",
      originalTitle: "Bates Motel",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMzk4OTU5NTE2M15BMl5BanBnXkFtZTcwNTIxMDIyOQ@@._V1_.jpg",
        width: 1538,
        height: 2048,
      },
      startYear: 2013,
      endYear: 2017,
      runtimeSeconds: 2700,
      genres: ["Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 8.1,
        voteCount: 123271,
      },
      plot: "An intimate look into the unraveling of Norman Bates' psyche throughout his teenage years.",
    },
    {
      id: "tt3743822",
      type: "tvSeries",
      primaryTitle: "Fear the Walking Dead",
      originalTitle: "Fear the Walking Dead",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMDU2YmNiOTktMjE4Ny00NmFhLWIxZTYtOWY0ZWQ4MWM3YjdiXkEyXkFqcGc@._V1_.jpg",
        width: 1013,
        height: 1500,
      },
      startYear: 2015,
      endYear: 2023,
      runtimeSeconds: 2640,
      genres: ["Drama", "Horror", "Sci-Fi", "Thriller"],
      rating: {
        aggregateRating: 6.8,
        voteCount: 151749,
      },
      plot: "A Walking Dead spinoff set in Los Angeles, California. Follows two families who must band together to survive the undead apocalypse.",
    },
    {
      id: "tt2628232",
      type: "tvSeries",
      primaryTitle: "Penny Dreadful",
      originalTitle: "Penny Dreadful",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZjkxMDAzMDgtNzFhNS00MjJkLWI5NTctZGRjODg3MzRiOWEzXkEyXkFqcGc@._V1_.jpg",
        width: 2400,
        height: 3263,
      },
      startYear: 2014,
      endYear: 2016,
      runtimeSeconds: 3600,
      genres: ["Drama", "Fantasy", "Horror"],
      rating: {
        aggregateRating: 8.2,
        voteCount: 137150,
      },
      plot: "Explorer Sir Malcolm Murray, American gunslinger Ethan Chandler, scientist Victor Frankenstein and medium Vanessa Ives unite to combat supernatural threats in Victorian London.",
    },
    {
      id: "tt27487379",
      type: "tvSeries",
      primaryTitle: "On the Run",
      originalTitle: "On the Run",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZGRiOWI5MjAtYWM1Ny00ZTVmLWI2MTMtMDlhZDFmMzIyMmVjXkEyXkFqcGc@._V1_.jpg",
        width: 2400,
        height: 3200,
      },
      startYear: 2025,
      genres: ["Action", "Drama", "Horror"],
      plot: "Five years post-apocalypse, a group flees continuously, seeking safety from an insidious new threat stalking the wasteland while navigating treacherous terrain and scavenging to survive.",
    },
    {
      id: "tt10691770",
      type: "tvSeries",
      primaryTitle: "Helluva Boss",
      originalTitle: "Helluva Boss",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BN2E1MGM3ZjEtYTQwMS00ZWUzLTk1NTctY2U4NzQzY2YwYWRmXkEyXkFqcGc@._V1_.jpg",
        width: 2000,
        height: 3000,
      },
      startYear: 2019,
      genres: [
        "Animation",
        "Action",
        "Comedy",
        "Crime",
        "Drama",
        "Fantasy",
        "Horror",
        "Music",
        "Musical",
        "Romance",
        "Sci-Fi",
      ],
      rating: {
        aggregateRating: 8.1,
        voteCount: 15244,
      },
      plot: "In Hell, imp Blitzø runs an assassin business targeting the world of the living, using a spell book borrowed from a prince of Hell. With employees Moxxie, Millie, and Loona, they attempt to survive each other while keeping business afloat.",
    },
    {
      id: "tt0318871",
      type: "tvSeries",
      primaryTitle: "Berserk",
      originalTitle: "Kenpuu Denki Berserk",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZmE1YTFlZWMtYzRkYi00MWU0LWIwODctZmYzMDExZGRkM2NmXkEyXkFqcGc@._V1_.jpg",
        width: 770,
        height: 1080,
      },
      startYear: 1997,
      endYear: 1998,
      runtimeSeconds: 1380,
      genres: [
        "Animation",
        "Action",
        "Adventure",
        "Drama",
        "Fantasy",
        "Horror",
        "Romance",
      ],
      rating: {
        aggregateRating: 8.7,
        voteCount: 70627,
      },
      plot: "Guts, a wandering mercenary, joins the Band of the Hawk after being defeated in a duel by Griffith, the group's leader and founder. Together, they dominate every battle, but something menacing lurks in the shadows.",
    },
    {
      id: "tt2654620",
      type: "tvSeries",
      primaryTitle: "The Strain",
      originalTitle: "The Strain",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYzlmNWU4OTMtMDY0My00MTI0LWFhNWItNzU0OGJhNWI0MDI3XkEyXkFqcGc@._V1_.jpg",
        width: 680,
        height: 1000,
      },
      startYear: 2014,
      endYear: 2017,
      runtimeSeconds: 2580,
      genres: ["Drama", "Fantasy", "Horror", "Thriller"],
      rating: {
        aggregateRating: 7.3,
        voteCount: 91408,
      },
      plot: "A mysterious viral outbreak with hallmarks of an ancient and evil strain of vampirism ravages the city of New York.",
    },
    {
      id: "tt2071645",
      type: "tvSeries",
      primaryTitle: "The Following",
      originalTitle: "The Following",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BYTQ3ZGYwMmItZTFkZS00NzdlLTg4NjctZTUyZmY4ZTM5MmUwXkEyXkFqcGc@._V1_.jpg",
        width: 1620,
        height: 2400,
      },
      startYear: 2013,
      endYear: 2015,
      runtimeSeconds: 2580,
      genres: ["Crime", "Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 7.4,
        voteCount: 94372,
      },
      plot: "A brilliant, charismatic, and psychotic serial killer communicates with other active serial killers and activates a cult of believers who follow his every command.",
    },
    {
      id: "tt5244362",
      type: "tvSeries",
      primaryTitle: "Färjan",
      originalTitle: "Färjan",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNzY3ZTI5ZWQtMDI1MC00ZTgxLThmYmMtZTRmYTRjZmMzYTI1XkEyXkFqcGc@._V1_.jpg",
        width: 2160,
        height: 3240,
      },
      startYear: 2025,
      genres: ["Drama", "Horror"],
      rating: {
        aggregateRating: 6.1,
        voteCount: 99,
      },
      plot: "Every night, all through the year, 1 200 passengers board Baltic Charisma for a cruise between Sweden and Finland. But tonight there is something evil on board the ship, and there is nowhere to escape.",
    },
    {
      id: "tt10875696",
      type: "tvSeries",
      primaryTitle: "Marianne",
      originalTitle: "Marianne",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZGZjYmQ4NzItMDA4Mi00ZjRjLWE3Y2ItYmY2ZTJkNmNhYTVmXkEyXkFqcGc@._V1_.jpg",
        width: 900,
        height: 1335,
      },
      startYear: 2019,
      endYear: 2019,
      runtimeSeconds: 3000,
      genres: ["Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 7.3,
        voteCount: 21040,
      },
      plot: "When a famous horror writer goes back to her hometown, she finds out that the evil spirit that plagues her dreams is also there in real life.",
    },
    {
      id: "tt5607616",
      type: "tvSeries",
      primaryTitle: "Re: Zero - Starting Life in Another World",
      originalTitle: "Re:Zero kara Hajimeru Isekai Seikatsu",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZWI4OTVkNDgtOTBmMC00M2I3LTk3NTctOWY3NmRkODIxMDViXkEyXkFqcGc@._V1_.jpg",
        width: 5610,
        height: 7948,
      },
      startYear: 2016,
      runtimeSeconds: 1440,
      genres: [
        "Animation",
        "Adventure",
        "Drama",
        "Fantasy",
        "Horror",
        "Mystery",
        "Romance",
        "Thriller",
      ],
      rating: {
        aggregateRating: 8.1,
        voteCount: 36725,
      },
      plot: "After being suddenly transported to another world, Subaru Natsuki and his new female partner are brutally murdered. However, Subaru awakens to a familiar scene, meeting the same girl again. The day begins to mysteriously repeat itself.",
    },
    {
      id: "tt14852808",
      type: "tvSeries",
      primaryTitle: "The Watcher",
      originalTitle: "The Watcher",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BOTRhNjhhMTEtY2U4Ni00Mzc4LTkwNzgtYmFmYmUzYWJkNzVmXkEyXkFqcGc@._V1_.jpg",
        width: 750,
        height: 1113,
      },
      startYear: 2022,
      endYear: 2022,
      genres: ["Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 6.5,
        voteCount: 90067,
      },
      plot: 'A married couple moving into their dream home are threatened by terrifying letters from a stalker, signed - "The Watcher.".',
    },
    {
      id: "tt8415836",
      type: "tvSeries",
      primaryTitle: "Guillermo del Toro's Cabinet of Curiosities",
      originalTitle: "Guillermo del Toro's Cabinet of Curiosities",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMjU2MzhjZjEtYTk4MS00OWRlLTgxYjEtZDA2MzAzNTkyNmU0XkEyXkFqcGc@._V1_.jpg",
        width: 1080,
        height: 1350,
      },
      startYear: 2022,
      endYear: 2022,
      runtimeSeconds: 3600,
      genres: ["Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 7,
        voteCount: 62267,
      },
      plot: "Bizarre nightmares unfold in eight tales of terror in a visually stunning, spine-tingling horror collection curated by Guillermo del Toro.",
    },
    {
      id: "tt2708480",
      type: "tvSeries",
      primaryTitle: "The Terror",
      originalTitle: "The Terror",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BNTUxNzI1MzcwN15BMl5BanBnXkFtZTgwMjA1MTg5NDM@._V1_.jpg",
        width: 1268,
        height: 1800,
      },
      startYear: 2018,
      endYear: 2025,
      runtimeSeconds: 3600,
      genres: ["Adventure", "Drama", "Horror", "Thriller"],
      rating: {
        aggregateRating: 7.8,
        voteCount: 59633,
      },
      plot: "Supernatural, semihistorical horror anthology series, where each season is inspired by a different infamous or mysterious real-life historical tragedy.",
    },
    {
      id: "tt12306692",
      type: "tvSeries",
      primaryTitle: "American Horror Stories",
      originalTitle: "American Horror Stories",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZTY4NTQ0ZDMtMGM4ZS00YmYwLWFkYmUtYWFlZmUwMTA5MWMyXkEyXkFqcGc@._V1_.jpg",
        width: 2004,
        height: 2500,
      },
      startYear: 2021,
      runtimeSeconds: 2700,
      genres: ["Drama", "Horror", "Mystery", "Thriller"],
      rating: {
        aggregateRating: 6.3,
        voteCount: 29019,
      },
      plot: "An anthology series of stand-alone episodes delving into horror myths, legends and lore.",
    },
    {
      id: "tt6517102",
      type: "tvSeries",
      primaryTitle: "Castlevania",
      originalTitle: "Castlevania",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BMjAzMjU2MjYzMl5BMl5BanBnXkFtZTgwNTQ4Nzk1NjM@._V1_.jpg",
        width: 1013,
        height: 1500,
      },
      startYear: 2017,
      endYear: 2021,
      runtimeSeconds: 1380,
      genres: [
        "Animation",
        "Action",
        "Adventure",
        "Drama",
        "Fantasy",
        "Horror",
      ],
      rating: {
        aggregateRating: 8.3,
        voteCount: 91301,
      },
      plot: "A vampire hunter fights to save a besieged city from an army of otherworldly creatures controlled by Dracula.",
    },
    {
      id: "tt11540908",
      type: "tvSeries",
      primaryTitle: "Carrie",
      originalTitle: "Carrie",
      primaryImage: {
        url: "https://m.media-amazon.com/images/M/MV5BZDdlZDdlNWYtZGVmOC00NzY4LWI0NDItODdiZDc0YmVjMzVjXkEyXkFqcGc@._V1_.jpg",
        width: 1430,
        height: 2048,
      },
      startYear: 2026,
      genres: ["Drama", "Horror"],
      plot: "A sheltered girl with telekinetic powers is bullied, leading to a horrific, bloody incident due to her domineering mother's influence.",
    },
  ],
  totalCount: 5793,
  nextPageToken:
    "eyJlc1Rva2VuIjpbIjIzNjIiLCIyMzYyIiwidHQxMTU0MDkwOCJdLCJmaWx0ZXIiOiJ7XCJjb25zdHJhaW50c1wiOntcImdlbnJlQ29uc3RyYWludFwiOntcImFsbEdlbnJlSWRzXCI6W1wiSG9ycm9yXCJdfSxcInRpdGxlVHlwZUNvbnN0cmFpbnRcIjp7XCJhbnlUaXRsZVR5cGVJZHNcIjpbXCJ0dlNlcmllc1wiXX19LFwibGFuZ3VhZ2VcIjpcImVuLVVTXCIsXCJzb3J0XCI6e1wic29ydEJ5XCI6XCJQT1BVTEFSSVRZXCIsXCJzb3J0T3JkZXJcIjpcIkFTQ1wifSxcInJlc3VsdEluZGV4XCI6NDl9In0=",
};

const TrendingNow = () => {
  return (
    <div className="container px-6 mt-6">
      <div>Trending Now</div>
      {movie_data && movie_data.titles && movie_data.titles.length > 0 ? (
        <MovieList movies={movie_data.titles} />
      ) : (
        <div>No movies were found.</div>
      )}
    </div>
  );
};

export default TrendingNow;
